// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2ufzRfyJIxUXvhRq6il_MNV6dE0XU1A',
    appId: '1:101294696454:web:2ce88894caa89ef3483b87',
    messagingSenderId: '101294696454',
    projectId: 'proiecttppm',
    authDomain: 'proiecttppm.firebaseapp.com',
    storageBucket: 'proiecttppm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcUvmcqaervJDj_GbN2YROkQx_0nnhTfk',
    appId: '1:101294696454:android:b1ae9a54e9c166c0483b87',
    messagingSenderId: '101294696454',
    projectId: 'proiecttppm',
    storageBucket: 'proiecttppm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfJ_gSZWjJQnY8f--0OU1v8l7_WFtrs8',
    appId: '1:101294696454:ios:63d9e1e45142791a483b87',
    messagingSenderId: '101294696454',
    projectId: 'proiecttppm',
    storageBucket: 'proiecttppm.appspot.com',
    iosClientId: '101294696454-4jkccfkngd09469nbf4fftmscbs1dn8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.proiectTppm',
  );
}
